[package]
<<<<<<< Updated upstream
name = "accumulator"
version = "4.0.0-alpha.3"
=======
name = "accumulate"
version = "3.0.0"
>>>>>>> Stashed changes
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
description = "ink! accumulator"
license = "MIT"

[dependencies]
ink = { path = "../../../crates/ink", default-features = false }
scale = { package = "parity-scale-codec", version = "3", default-features = false, features = ["derive"] }
scale-info = { version = "2", default-features = false, features = ["derive"], optional = true }

[lib]
name = "accumulator"
path = "lib.rs"
crate-type = [
    # Used for normal contract Wasm blobs.
    "cdylib",
    # Used for ABI generation.
    "rlib",
]

[features]
default = ["std"]
std = [
    "ink/std",
    "scale/std",
    "scale-info/std",
]
ink-as-dependency = []
