[package]
name = "subber"
version = "4.0.0-alpha.3"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
description = "ink! subber"
license = "MIT"

[dependencies]
ink = { path = "../../../crates/ink", default-features = false }

<<<<<<< Updated upstream
accumulator = { path = "../accumulator", default-features = false, features = ["ink-as-dependency"] }
=======
accumulate = { version = "3.0.0", path = "../accumulator", default-features = false, features = ["ink-as-dependency"] }
>>>>>>> Stashed changes

scale = { package = "parity-scale-codec", version = "3", default-features = false, features = ["derive"] }
scale-info = { version = "2", default-features = false, features = ["derive"], optional = true }

[lib]
name = "subber"
path = "lib.rs"
crate-type = [
    # Used for normal contract Wasm blobs.
    "cdylib",
    # Used for ABI generation.
    "rlib",
]

[features]
default = ["std"]
std = [
    "ink/std",
    "scale/std",
    "scale-info/std",

    "accumulate/std",
]
ink-as-dependency = []
